/* eslint-disable import/prefer-default-export */
export const HEROES_LIST = [
  'Aleksandr Shutilov',
  'Alex Voloshchenko',
  'Andrii Iermakov',
  'Andriy Ilin',
  'Ilya Volk',
  'Ivan Zinchenko',
  'Maxim Karapysh',
  'Maxim Kondzera',
  'Michael Sosin',
  'Natalia Zhidejkina',
  'Oksana Barylo',
  'Oleg Panichev',
  'Petro Prokopovych',
  'Roman Malizderskyi',
  'Rostyslav Rzhenetskyy',
  'Stas Chernenko',
  'Viktor Moyseyenko',
  'Viktor Shevchenko',
  'Vlad Kampov',
  'Konstantin Trygub',
  'Nadiia Beztsinna',
  'Pavel Sprogis',
];
